//addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.1.0")
addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.2.1")
//addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "2.0")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.9.21")
//addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.2")
//addSbtPlugin("se.marcuslonnberg" % "sbt-docker" % "1.5.0")
addSbtPlugin("se.marcuslonnberg" % "sbt-docker" % "1.9.0")
//addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.5")
//addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "2.1.1")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "2.2.0")
//addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.7.0")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.12.0")
//addSbtPlugin("com.47deg"  % "sbt-microsites" % "0.7.13")
//addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "2.0.9")

libraryDependencies += "org.apache.commons" % "commons-compress" % "1.8"
